---
# tasks file for postgres
- name: Install PostgreSQL packages
  apt:
    name: "{{ postgresql_packages }}"
    state: present
  become: true

- name: Ensure PostgreSQL is enabled and started
  service:
    name: "{{ postgresql_service_name }}"
    state: started
    enabled: true
  become: true

- name: Configure PostgreSQL
  template:
    src: postgresql.conf.j2
    dest: "{{ postgresql_data_dir }}/postgresql.conf"
    owner: postgres
    group: postgres
    mode: 0644
  notify: Restart PostgreSQL
  become: true

- name: Set PostgreSQL password for user
  become_user: "{{ postgresql_user }}"
  shell:
    cmd: |
      psql -c "ALTER USER {{ postgresql_user }} PASSWORD '{{ postgresql_password }}';"
  when: postgresql_password is defined